name: TCPConnector
description: A sample Chrome packaged application
dependencies:
  chrome: any
transformers:
- chrome
- $dart2js:
    checked: false
    minify: true
    verbose: false
    analyzeAll: false
    suppressWarnings: false
    suppressHints: false
    terse: false